### ISSUE TITLE
Goldhen update for 2.4b16

### ISSUE THREAD

**Issue by saildot4k** [kmeps4/Kme900_Auto_ESP32_S2#4]
Would you kindly update for Goldhen 2.4b16? I still prefer my ESP32-S2 solution...

**Comment by ameeno** [comment]
Can manually change the bin via admin interface simply rename the bin file

**Comment by ameeno** [comment]
Also would it be possible to add psfree to this build @kmeps4

**Comment by mihaiaka** [comment]
+1 more waiting for the psfree + latest hen version

**Comment by ameeno** [comment]
Oooh thanks for the reminder, I saw on @kmeps4 's twitter (x) to expect a new esp32 build over the weekend, but sadly repo is not yet updated.

**Comment by mihaiaka** [comment]
do you guys know what the "ESP web flasher" button does, from https://www.kmeps4.site/
It will take me here:
https://www.kmeps4.site/EspWeb/index.html
I'm assuming it's not related to this S2 project but to something else? Thank you.

**Comment by kmeps4** [comment]
Hi... I'll update the S2 code soon.. ESP web Flasher allows you to delete and flash any bin file to your boards.. it's a easy to use web approach by Adafruit

**Comment by mihaiaka** [comment]
can one send you some ko-fi? @kmeps4

**Comment by saildot4k** [comment]
It flashes a precompiled bin to an esp32, made via arguing ide. I updated
both bin and source to goldhen2.4b16 but now need to update to
goldhen2.4b16.2 and reupload
